print("Hello python")
print("hello again")
print("to print use print funtion")
print("Hello again")
print("I like typing this.")
print("This is fun.")
print("Yay! Printing")
print("I'd much rather you not")
print('I "said" do not touch this')

